/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$xitrum_scalate_string_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      val helper: xitrum.Action = $_scalate_$_context.attribute("helper")
      import helper._
      ;{
        val context: org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
        import context._
        
        
        $_scalate_$_context << ""
      }
    }
  }
}


class $_scalate_$xitrum_scalate_string_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$xitrum_scalate_string_ssp.$_scalate_$render(context)
}
